services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Bind mount for custom config
      - prometheus-data:/prometheus  # Named volume for persistent data storage
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Specify the config file

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana

  flask-app:
    build: .
    env_file:
      - env.env
    ports:
      - "5000:5000"

volumes:
  prometheus-data:  # Define the named volume for Prometheus
  grafana_data:  # Define the named volume for Grafana
